## CHANGE this to the name of your plugin.
name: FlowerPower

## CHANGE this to your username.
author: NCBPFluffyBear

## CHANGE this to a meaninful but short description of your plugin.
description: A Slimefun4-Addon that adds more magical options

## CHANGE this to the path of the class that extends JavaPlugin.
main: io.ncbpfluffybear.flowerpower.FlowerPowerPlugin

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/NCBPFluffyBear/Magic

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.16

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun